site_name: Lofyer's Blog
site_url: https://docs.lofyer.org
site_author: lofyer
repo_name: lofyer/lofyer.github.io
repo_url: https://github.com/lofyer/lofyer.github.io
edit_uri: ""
copyright: Copyright &copy; 2008 - 2022 lofyer

nav:
  - Index: index.md
  - Lab:
    - 产品与市场:
      - 产品如何定价的模型讨论: blog/Lab/3-产品如何定价.md
      - 关于产品的一点思考: blog/Lab/27-关于产品的一点思考.md
      - ZStack的产品化之路（PR文）: blog/Lab/40-zstack-product.md
    - 云计算: 
      - Android虚拟化技术实现: blog/Lab/19-android-kvm.md
      - ZStack集成: blog/Lab/14-zstack.md
      - 去重软件测试OpenDedup: blog/Lab/15-opendedup.md
      - 当代ARM/X86服务器中的Android: blog/Lab/19-android-kvm.md
      - 开源备份工具的选择: blog/Lab/20-backup-tools.md
      - 适合云计算的高性能NVMe存储探索: blog/Lab/30-nvme-in-the-cloud.md
      - OpenStack中对接Pica8交换机: blog/Lab/31-openstack-opendaylight-pica8.md
      - oVirt虚拟化笔记: blog/Lab/32-ovirt.md
      - OpenWRT固件使用ovs（自制SDN交换机）: blog/Lab/33-ovs-in-openwrt.md
      - 实时操作系统的K8s平台: blog/Lab/35-realtime-k8s.md
      - VMware Converter SDK初探: blog/Lab/39-vmware-convert-sdk.md
    - 裸金属:
      - 构建自用裸金属（RPI、OpenBMC、FPGA、BF2）: blog/Lab/5-baremetal.md
      - 基于FPGA的物理机容错探索: blog/Lab/16-fpga-ft.md
      - FPGA测试: blog/Lab/17-fpga-test.md
    - 软件定义无线电: blog/Lab/37-sdr.md
    - 高性能计算:
      - HPC笔记: blog/Lab/7-hpc.md
      - 探索路径之负载自动化云平台PID控制器: blog/Lab/13-cloud-pid-controller.md
      - 高性能本地VDI: blog/Lab/41-这社会进步快.md
    - 其他技术记录:
      - 3C数码: blog/Lab/1-3c.md 
      - Arduino: blog/Lab/4-arduino.md
      - LeapMotion: blog/Lab/8-leapmotion.md
      - NVIDIA Jetson: blog/Lab/10-nvidia-jetson.md
      - RaspberryPi: blog/Lab/28-gpu-raspberry-pi.md
      - IPFS/Filecoin: blog/Lab/29-lotus-howto.md
      - IT应用与服务: blog/Lab/38-server.md
      - 临时笔记: blog/Lab/34-quick-notes.md
      - Rex: blog/Lab/36-rex.md
  - ABM:
    - ABM学习笔记: blog/ABM/abm-note.md
    - 应用外汇学习笔记: blog/ABM/forex-note.md
  #- 500PX: https://500px.com.cn/lofyer
  - Docs:
    - DataNote:
        - datanote/index.md
        - 第一章 数据收集、统计: datanote/ch01.md
        - 第二章 机器学习基础: datanote/ch02.md
        - 第三章 ABM建模基础: datanote/ch03.md
        - 第四章 数据处理平台: datanote/ch04.md
        - 第五章 外汇交易基础: datanote/ch05.md
        - 第六章 信号交易系统: datanote/ch06.md
        - 第七章 指导白皮书: datanote/ch07.md
        - 第八章 代理人模型: datanote/ch08.md
        - 关于: datanote/about.md
    - InTheCloud:
        - inthecloud/index.md
        - 第一章 随便说些什么: inthecloud/ch01.md
        - 第二章 一个可靠的存储后端: inthecloud/ch02.md
        - 第三章 合适的虚拟化平台: inthecloud/ch03.md
        - 第四章 数据抓取与机器学习算法: inthecloud/ch04.md
        - 第五章 数据处理平台: inthecloud/ch05.md
        - 附录一 OpenStack概念、部署、与高级网络应用: inthecloud/appendix01.md
        - 附录二 公有云参考: inthecloud/appendix02.md
        - 附录三 PaaS/OpenShif: inthecloud/appendix03.md
        - 附录四  Docker 使用及自建repo: inthecloud/appendix04.md
        - 附录五 常用功能运维工具: inthecloud/appendix05.md
        - 附录六 文档参考资源以及建议书单: inthecloud/appendix06.md
        - 待整理扩展内容: inthecloud/appendix07.md
        - 关于作者与文档: inthecloud/about.md
        - 《运维前线》私有云桌面网络组建草稿: inthecloud/frontline-network.md
        - 《运维前线》虚拟化存储启动风暴草稿: inthecloud/frontline-storage.md
    - WangSheng:
        - wangsheng/index.md
  - Tags: tags.md
  - About: about/about.md
  - Template: template_password.md
  - Blog:
    - blog/index.md

theme:
  name: material
  custom_dir: !ENV [THEME_DIR, "overrides/"]
  language: zh
  favicon: images/favicon.ico
  font: false
  features:
    #- navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.tracking
    #- navigation.indexes
    #- navigation.instant
    - search.suggest
    - search.highlight
    - search.share
    #- toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Light mode

plugins:
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - search:
      lang: zh
  - awesome-pages:
      collapse_single_pages: false
  #- mkdocs-jupyter:
  #    include_source: True
  - encryptcontent:
      remember_password: True
      #default_expire_dalay: 24
      #global_password: 'P@ssw0rd'
      title_prefix: '[密码保护]'
      summary: '内容已被加密保护，请输入密码后访问'
      placeholder: '输入密码'
      decryption_failure_message: '密码无效！'
      encryption_info_message: '联系管理员获取访问密码'
      password_button: True
      password_button_text: '确认密码'
  - search: {}
  - blog:
      blog_dir: blog
      #blog_toc: true
      post_url_date_format: yyyy/MM/dd
      post_readtime_words_per_minute: 265


  #- blog:
  #    folder: blog
  #     articles: 50
  #    format: "(%y/%m/%d)"
  #     text-align: "right"
  #     display-more-articles: true
  #     display-article-date: true
  #     pagination: "Page % of %"
  #     more-articles: "More articles(%)"
  # - macros:
  #   include_dir: snippets

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - meta

extra:
  disqus: lofyer

extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
